FROM openjdk:8-jdk-alpine
EXPOSE 8888

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Seoul

RUN apt-get install -y tzdata

ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=local", "-Djasypt.encryptor.password=wogml23", "/app.jar"]